### ISSUE TITLE
额。。。看不懂，反爬？

### ISSUE THREAD

**Issue by z1461328410** [videoDown123/xiaoeknow_download#2]
1-2_项目技术栈和架构图 v_6353f484e4b0c94264a6f63a
Traceback (most recent call last):
  File "小鹅通已购批量下载v7.py", line 16, in <module>
  File "<frozen demo>", line 852, in download_main
  File "<frozen demo>", line 734, in e_yigou_begin_
  File "<frozen demo>", line 204, in begin_down_url
  File "<frozen demo>", line 379, in P_xiao_muLu
  File "<frozen demo>", line 485, in resource_info_
  File "requests\models.py", line 910, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
[9160] Failed to execute script '小鹅通已购批量下载v7' due to unhandled exception!

**Comment by UltimateKK** [comment]
有解决方法吗？ @coco-repository

**Comment by coco-repository** [comment]
> 有解决方法吗？ @coco-repository 
自己抓包写了一个批量下载工具

**Comment by UltimateKK** [comment]
工具可以分享吗？或者方便教一下？ @coco-repository 

> > 有解决方法吗？ @coco-repository
> > 自己抓包写了一个批量下载工具

**Comment by coco-repository** [comment]
> 工具可以分享吗？或者方便教一下？ @coco-repository 
> 
> > > 有解决方法吗？ @coco-repository
> > > 自己抓包写了一个批量下载工具
> 

自用，不打算公开，人多了担心接口失效，但有时间了能帮你下
